### ISSUE TITLE
SecurityError: Permission denied to access property "pathname" on cross-origin object

### ISSUE THREAD

**Issue by jeph864** [DatabayAG/EtherCalc#1]
I'm trying to use the export function of ethercalc but this error kept appearing. I'm aware that the error rises from a javascript's conflicts with CORS since ethercalc server and ILIAS are running on different domains. I have tried to solve it by setting response headers in the ILIAS backend(allow cross-origin ), but this did not work. 
Any idea how to solve this?

**Comment by gvollbach** [comment]
Setting the headers should work, but as an alternative the ethercalc id should be listed on the info tab in ILIAS, so you can access the pad directly. But since this is no bug in general I close this issue.
