### ISSUE TITLE
ILIAS 7 Support

### ISSUE THREAD

**Issue by maxjacobs283** [DatabayAG/EtherCalc#2]
Hello,
I would like to ask if ILIAS 7 Support is planned and if there is already an ETA for it

**Comment by gvollbach** [comment]
At the moment this is the first request for ILIAS 7 support for this plugin, so no there is no ETA at the moment for ILIAS 7 compatibility, if you are willing to finance this update, your are welcome to contact us.

**Comment by gvollbach** [comment]
In the meantime the plugin is compatible with ILIAS 7 and 8.
